spring.application.name=workspace-service
server.port=8082

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/flowboard_workspace?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=${REDIS_TIMEOUT:2s}
spring.data.redis.repositories.enabled=false
spring.cache.type=redis
spring.cache.redis.time-to-live=${CACHE_TTL:10m}
spring.cache.redis.cache-null-values=false


# Kafka Configuration
spring.kafka.producer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Eureka & Admin Client
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=${HOSTNAME:localhost}
eureka.instance.prefer-ip-address=true
spring.boot.admin.client.url=${ADMIN_SERVER_URL:http://localhost:9090}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.redis.enabled=false
payment.service.base-url=${PAYMENT_SERVICE_BASE_URL:http://localhost:8089/api/v1/internal/payments}
board.service.base-url=${BOARD_SERVICE_BASE_URL:http://localhost:8083/api/v1/boards/internal}
app.plan.free-workspace-limit=${FREE_WORKSPACE_LIMIT:5}
app.plan.free-member-limit=${FREE_MEMBER_LIMIT:5}
